news_sites:
  eluniversal:
    url: https://www.eluniversal.com.mx/
    queries:
      homepage_article_links: '.field-content a'

  elpais:
    url: https://elpais.com/america/
    queries:
      homepage_article_links: '.headline a'
